"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Database, LoaderCircle, Pin, PinOff, Play, Trash2 } from "lucide-react";

type Asset = { id: string; videoId: string; fileSize: string | null; status: string; pinned: boolean; protected: boolean; lastAccessedAt: string | null; cachedAt: string | null; video: { title: string; youtubeId: string; sources: Array<{ source: { id: string; name: string } }> } };
type Dashboard = { maxBytes: string; maxAgeDays: number; totalBytes: string; protectedBytes: string; pinnedBytes: string; evictableBytes: string; activeJobs: number; assets: Asset[] };
function bytes(value: string) { const amount = Number(value); if (!amount) return "0 B"; const units = ["B", "KB", "MB", "GB", "TB"]; const index = Math.min(units.length - 1, Math.floor(Math.log(amount) / Math.log(1024))); return `${(amount / 1024 ** index).toFixed(index > 2 ? 1 : 0)} ${units[index]}`; }

export function CacheDashboard({ initial }: { initial: Dashboard }) {
  const router = useRouter(); const [busy, setBusy] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const percent = Math.min(100, Number(initial.totalBytes) / Math.max(1, Number(initial.maxBytes)) * 100);
  async function action(url: string, body: object, key: string) { setBusy(key); setError(null); try { const response = await fetch(url, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result.error?.message ?? "Cache operation failed"); router.refresh(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Cache operation failed"); } finally { setBusy(null); } }
  async function assetAction(asset: Asset, name: "pin" | "unpin" | "evict") { if (name === "evict" && !window.confirm(`Evict ${asset.video.title}?`)) return; setBusy(asset.id); setError(null); try { const response = await fetch(`/api/cache/${asset.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: name }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error?.message ?? "Cache operation failed"); router.refresh(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Cache operation failed"); } finally { setBusy(null); } }
  async function play(asset: Asset) { const source = asset.video.sources[0]?.source; if (!source) return; const response = await fetch("/api/playback/prepare", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ sourceId: source.id, videoId: asset.videoId }) }); const result = await response.json(); if (response.ok && result.data.state === "ready") window.open(result.data.playbackUrl, "_blank", "noopener,noreferrer"); }
  return <><div className="stat-grid"><div className="stat"><span>Used</span><strong>{bytes(initial.totalBytes)}</strong></div><div className="stat"><span>Tunarr protected</span><strong>{bytes(initial.protectedBytes)}</strong></div><div className="stat"><span>Pinned</span><strong>{bytes(initial.pinnedBytes)}</strong></div><div className="stat"><span>Evictable</span><strong>{bytes(initial.evictableBytes)}</strong></div></div><div className="meter" aria-label={`${percent.toFixed(0)}% cache used`}><span style={{ width: `${percent}%` }}/></div><div className="toolbar"><span className="muted">Limit {bytes(initial.maxBytes)} · {initial.maxAgeDays} idle days · {initial.activeJobs} active jobs</span><span className="spacer"/><button className="button secondary" disabled={Boolean(busy)} onClick={() => action("/api/cache", { action: "enforce" }, "enforce")}>{busy === "enforce" ? <LoaderCircle size={14} className="animate-spin"/> : <Database size={14}/>} Enforce limits</button><button className="button secondary" disabled={Boolean(busy)} onClick={() => window.confirm("Clear every evictable cache asset?") && action("/api/cache", { action: "clear" }, "clear")}><Trash2 size={14}/> Clear evictable</button></div>{Number(initial.totalBytes) > Number(initial.maxBytes) && Number(initial.evictableBytes) === 0 ? <div className="error">Protected assets exceed the cache limit. Unlink a Tunarr source or unpin assets to make space.</div> : null}{error ? <div className="error">{error}</div> : null}{initial.assets.length ? <div className="table-wrap"><table><thead><tr><th>Video</th><th>Size</th><th>Last used</th><th>State</th><th>Actions</th></tr></thead><tbody>{initial.assets.map((asset) => <tr key={asset.id}><td className="title-cell"><strong>{asset.video.title}</strong><span className="meta">{asset.video.sources.map((item) => item.source.name).join(", ") || asset.video.youtubeId}</span></td><td>{bytes(asset.fileSize ?? "0")}</td><td>{asset.lastAccessedAt ? new Date(asset.lastAccessedAt).toLocaleString() : "Never"}</td><td><span className={`badge ${asset.status}`}>{asset.protected ? "Tunarr protected" : asset.pinned ? "Pinned" : asset.status.replaceAll("_", " ")}</span></td><td><div className="toolbar"><button className="button secondary" disabled={Boolean(busy)} onClick={() => play(asset)} aria-label={`Play ${asset.video.title}`}><Play size={14}/></button><button className="button secondary" disabled={Boolean(busy)} onClick={() => assetAction(asset, asset.pinned ? "unpin" : "pin")} aria-label={asset.pinned ? "Unpin" : "Pin"}>{asset.pinned ? <PinOff size={14}/> : <Pin size={14}/>}</button><button className="button secondary" disabled={Boolean(busy) || asset.protected || asset.pinned} onClick={() => assetAction(asset, "evict")} aria-label="Evict"><Trash2 size={14}/></button></div></td></tr>)}</tbody></table></div> : <div className="empty"><Database size={32}/><h2>Cache is empty</h2><p>Cache-mode videos appear here after their first playback.</p></div>}</>;
}
