"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { LoaderCircle, Save } from "lucide-react";
import { VIDEO_QUALITY_OPTIONS } from "@/components/settings-form";

export function SourceSettings({ sourceId, initialMode, initialVideoQuality, initialSyncEnabled, initialInterval, supportsSync = true }: { sourceId: string; initialMode: string; initialVideoQuality: string | null; initialSyncEnabled: boolean; initialInterval: number; supportsSync?: boolean }) {
  const router = useRouter(); const [mode, setMode] = useState(initialMode); const [videoQuality, setVideoQuality] = useState(initialVideoQuality ?? ""); const [enabled, setEnabled] = useState(initialSyncEnabled); const [interval, setIntervalValue] = useState(String(initialInterval)); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null);
  async function save() {
    setBusy(true); setMessage(null);
    try { const response = await fetch(`/api/sources/${sourceId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ playbackMode: mode, videoQuality: videoQuality || null, ...(supportsSync ? { syncEnabled: enabled, syncIntervalMinutes: Number(interval) } : {}) }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? "Save failed"); setMessage("Source settings saved."); router.refresh(); }
    catch (error) { setMessage(error instanceof Error ? error.message : "Save failed"); } finally { setBusy(false); }
  }
  return <section className="card integration-card"><h2>{supportsSync ? "Playback and synchronization" : "Playback"}</h2><div className="form-grid"><div className="field"><label htmlFor="source-mode">Playback mode</label><select id="source-mode" className="input" value={mode} onChange={(event) => setMode(event.target.value)}><option value="download">Permanent</option><option value="cache">Cache on first play</option><option value="stream">Stream on demand</option></select></div><div className="field"><label htmlFor="source-video-quality">Video quality</label><select id="source-video-quality" className="input" value={videoQuality} onChange={(event) => setVideoQuality(event.target.value)}><option value="">Use default (from Settings)</option>{VIDEO_QUALITY_OPTIONS.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></div>{supportsSync ? <><label className="choice"><span><input type="checkbox" checked={enabled} onChange={(event) => setEnabled(event.target.checked)} /> Automatic sync</span></label><div className="field"><label htmlFor="sync-interval">Interval</label><select id="sync-interval" className="input" value={interval} disabled={!enabled} onChange={(event) => setIntervalValue(event.target.value)}><option value="60">Hourly</option><option value="360">6 hours</option><option value="720">12 hours</option><option value="1440">Daily</option><option value="10080">Weekly</option></select></div></> : <p>Curated collections change only when you add videos.</p>}</div><button className="button secondary" disabled={busy} onClick={save}>{busy ? <LoaderCircle size={14} className="animate-spin"/> : <Save size={14}/>} Save</button>{message ? <p className={message.includes("saved") ? "success" : "error"}>{message}</p> : null}</section>;
}
